# 网站图标
favicon:
  enable: true
  icon: /images/favicon.jpeg
  touch_icon: /images/favicon.jpeg

# 用户头像与昵称
avatar:
  author_photo: /images/avatar.jpeg
  author_nickname: ericpuwang
  path: /


# Google 分析
# https://analytics.google.com
# 注册Google分析账号，在管理/创建媒体资源/选择网站/填写相关信息后得到跟踪Id，一般格式为UA-xxxxxxx-x
# 如之前已有注册账号，在管理/跟踪信息/跟踪代码/找到跟踪ID，一般格式为UA-xxxxxxx-x
gtag:
  enable: false
  gtagkey: ''

# 文章评论系统
comments:
  enable: false

# 主题页面导航栏
navbar:
  -
    name: Home
    enable: true
    path: /
    key: home
  -
    name: Archives
    enable: true
    path: /archives/
    key: archives
  -
    name: Categories
    enable: false
    path: /categories/
    key: categories
  -
    name: Tags
    enable: true
    path: /tags/
    key: tags
  -
    name: Friends
    enable: false
    path: /friends/
    key: friends
  -
    name: About
    enable: false
    path: /about/
    key: about

# 文章目录
catalog:
  enable: true

# 文章末尾的上一页与下一页
prevnext:
  enable: true

# 页脚信息
footer:
  social: ''
  more: ''

# 文章搜索
search:
  enable: true
  placeholder: 

# 深/浅配色切换
colorSwitch:
  enable: true

# 文章分享
postShare:
  enable: true

  twitter:
    enable: true

  facebook:
    enable: true

# 代码块配置
codeBlock:
  # 代码块风格，默认normal
  # 可选：默认风格'normal'；mac黑色风格：'mac-black'
  style: 'normal'
  # 代码复制
  copy:
    enable: true

# MathJax Support
# 数学公式支持
mathjax:
  enable: true

# 主题色
themeColor: '#808080'
